version: '3.7'

services:
    grafana:
        image: grafana/grafana
        network_mode: host
        ports:
            - '3555:3000' # Public port
        volumes:
            - type: bind
              source: ./config
              target: /etc/grafana
